### PR TITLE
Fix Comparators' bridge

### PR DESCRIPTION
**Pull request by Lassebq**
I guess I'll PR this because I don't have anything else to contribute

### CODE REVIEW

**Comment by Geolykt** [comment]
Just for the record (haven't performed any testing yet) it is likely that this PR in the current state needs to be changed as we use the output from Sl-deobf for running jars (as well as linking) and not just for decompiling (decompliation is really just a neat extra).
However removing Comparator#compre(Object, Object) will invalidate any references to that method and will likely throw a runtime error when it is referenced.

I'm current taking a break but I should hopefully see whether it really works a few days later (hopefully tomorrow, but could also be at the end of this week)

**Review by Geolykt — CHANGES_REQUESTED** [review]
This change would break jars, thus breaking exactly what this method was designed to repair.
Screenshot from 2022-06-12 21-56-23

**Comment by Lassebq** [comment]
Oh, just so you know, I didn't test this change by running the edited jar, only exported source. Without this modification it caused name conflicts between bridge and the method it's bridging to.
I'll see if I can do anything about this.

**Comment by Lassebq** [comment]
Okay, so I don't think there's anything that can be done on the bytecode level to keep it functional, only by modifying decompiler behavior.

**Pull request closed without merging**
